### ISSUE TITLE
Chunks are not preserved.

### ISSUE THREAD

**Issue by jmunozzz** [stream-utils/duplex-child-process#10]
I have this small js script.

```
const childProcess = require('duplex-child-process');
const { Readable, Transform } = require('stream');

const reader = new Readable({
    encoding: 'utf-8',
});

const transformer = new Transform({
    transform: (chunk, encoding, callback) => {
        console.log('chunk:', chunk.toString());
        callback(null, chunk);
    }
});

reader
  .pipe(childProcess.spawn('./hellowolrd.py'))
  .pipe(transformer)

reader.push('This is a test.\n');
reader.push('This is a test.\n');
reader.push('This is a test.\n');
reader.push(null);
```

It calls this small python script that just write stdin to sdout.

```
#!/usr/bin/env python3
import sys

def main():
    for line in sys.stdin:
        sys.stdout.write(line)

if __name__ == '__main__':
    main()
```

I'm expecting to have this result: 

```
chunk: This is a test.
chunk: This is a test.
chunk: This is a test.
```

But I have this: 

```
chunk: This is a test.
This is a test.
This is a test.
```

It seems that chunks are concatenated before being sent to the next stream.
Is this normal behaviour ?

**Comment by jeromew** [comment]
Hello,
thanks for the report.

I am not sure that the stream API gives any kind of guarantee regarding such boundaries.

It would be interesting to test this without using the `duplex-child-process` module to see what happens but I suspect you would get the same result. At this stage I don't see where `duplex-child-process` would buffer/concatenate the chunks.

what happens when you remove `.pipe(childProcess.spawn('./hellowolrd.py'))` in the code ?

**Comment by jmunozzz** [comment]
Without it, chuncks leave as they enter.
We would have
```
chunk: This is a test.

chunk: This is a test.

chunk: This is a test.
```

**Comment by jeromew** [comment]
I am not too surprised by such re-chunking and I don't think you can expect a chunk by chunk execution all the way down the pipeline across processes. Does the buffer block until `reader.push(null);` is called ?

**Comment by jeromew** [comment]
it could also be due to that fact that `childProcess.spawn('./hellowolrd.py')` takes a bit of time for the python script to start. So the calls to push get buffered internally in the `reader` or in the stream that wraps the python script until everything is started.

There is probably a way to start pushing only when the script has started and is ready to accept input data.

**Comment by jeromew** [comment]
Tell me if you did more tests. It seems that there is no real way to make sure that the sub-process has finished its startup phase. cf discussion on https://github.com/nodejs/help/issues/1191

you might try to confirm that this is a timing issue by adding writes to `sys.stdout` before the for loop in your python script and see where this happens compared to the `push` calls.

But in any case, I would not rely the fact that the chunks flow one-after-the-other. There is no such guarantee in process pipelines to the best of my knowledge. As for as I know, the chunks could even be split.

**Comment by jmunozzz** [comment]
Thanks for the answer.
I'll use a workaround by piping child-process output to another transformer that rearrange chunks line per line.
 I'lI let you know the results of additional tests.

**Comment by jeromew** [comment]
I close this issue for now. Feel free to re-open if you have more info.
